# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: reach-app/package-lock.json
    - run: npm i -g zcatalyst-cli
    - run: npm install
      working-directory: ./react-app
    - run: catalyst deploy --verbose --project sample-project --org 857063863 --token m_1004.b3a3409c030101cabe2aa7c45829bdfc.8d581ce5ae55ca7cc81027dd527ead75
    env:
        CI: false

